[package]
name = "dormouse-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["cpu"]
cpu = ["dormouse-train/cpu"]
cuda = ["dormouse-core/cuda", "dormouse-train/cuda"]

[dependencies]
dormouse-core = { path = "../dormouse-core" }
dormouse-train = { path = "../dormouse-train", default-features = false }
clap = { workspace = true, features = ["derive"] }
libc = "0.2"
rand = { workspace = true }
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { workspace = true, features = ["derive"] }
