// Astro + Starlight config for the dormouse knowledge base.
//
// Every page under src/content/docs/ is GENERATED by tools/ingest.mjs from a
// canonical file in this repo. Edit the source file, not the page; see IA.md.
// Hand-rolled rather than `npm create astro@latest` because the scaffolder is
// interactive and writes a template this config would immediately replace.
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import manifest from './tools/manifest.mjs';

const { repo } = manifest;

export default defineConfig({
	site: `${repo}`,
	trailingSlash: 'always',
	integrations: [
		starlight({
			title: 'dormouse',
			description:
				'A byte-level language-model trainer that fits on one workstation — published with the measurements that justify it and the ones that refute it.',
			// English is the default and nothing is translated: 387 documents
			// exist in two languages and a machine translation of them would be a
			// second source of truth in a second language. See IA.md.
			defaultLocale: 'en',
			social: [{ icon: 'github', label: 'GitHub', href: repo }],
			// "Edit page" is per-page: the ingest step writes `editUrl` in each
			// generated page's frontmatter, pointing at the CANONICAL file on
			// GitHub and never at the generated one (which is gitignored).
			customCss: ['./src/styles/custom.css'],
			components: {
				// The site has one author and one repo; a footer credit is noise.
				Footer: undefined,
			},
			head: [
				{
					tag: 'link',
					attrs: {
						rel: 'icon',
						type: 'image/svg+xml',
						href: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22%3E%3Ctext y=%22.9em%22 font-size=%2290%22%3E%F0%9F%90%B9%3C/text%3E%3C/svg%3E',
					},
				},
			],
		}),
	],
});