// Astro + Starlight config for the dormouse knowledge base.
//
// Every page under src/content/docs/ is GENERATED by tools/ingest.mjs from a
// canonical file in this repo. Edit the source file, not the page; see IA.md.
// Hand-rolled rather than `npm create astro@latest` because the scaffolder is
// interactive and writes a template this config would immediately replace.
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';
import manifest from './tools/manifest.mjs';

const { repo } = manifest;

export default defineConfig({
	site: `${repo}`,
	// GitHub Pages project site: served under /dormouse/ — without this every asset 404s.
	base: '/dormouse',
	trailingSlash: 'always',
	integrations: [
		// Mermaid renders ```mermaid fences client-side. The owner directive is
		// that ASCII box-drawing diagrams are always broken (a code block is
		// monospace-proportional to the reader's font and nothing lines up), so
		// this is the lane that makes a diagram worth writing. A mermaid fence
		// that mermaid cannot parse still renders as its own source, so a bad
		// diagram is a visible bad diagram rather than a silent one.
		mermaid({ theme: 'neutral', autoTheme: true }),
		starlight({
			title: 'dormouse',
			description:
				'A byte-level language-model trainer that fits on one workstation — published with the measurements that justify it and the ones that refute it.',
			// English, and nothing is translated. `defaultLocale` is deliberately
			// NOT set: it is Starlight's switch for i18n ROUTING, and setting it
			// makes Astro look for an `i18n` content collection this site does not
			// have, warning on every build ("collection i18n does not exist or is
			// empty"). Without it the root locale is English and URLs are unprefixed
			// — the same result, no warning. ~180 documents exist in two languages
			// and a machine translation of them would be a second source of truth in
			// a second language; see IA.md.
			social: [{ icon: 'github', label: 'GitHub', href: repo }],
			// "Edit page" is per-page: the ingest step writes `editUrl` in each
			// generated page's frontmatter, pointing at the CANONICAL file on
			// GitHub and never at the generated one (which is gitignored).
			customCss: ['./src/styles/custom.css'],
			// Starlight's default is /favicon.svg, which is the extension it accepts;
			// public/favicon.svg IS the hamster, so the link resolves instead of
			// dangling on all 181 pages.
			favicon: '/favicon.svg',
			components: {
				// The site has one author and one repo; a footer credit is noise.
				Footer: undefined,
			},
		}),
	],
});